global:
  scrape_interval: 15s # 기본 스크랩 간격
  evaluation_interval: 15s # 규칙 평가 간격

scrape_configs:
  - job_name: "prometheus" # Prometheus 자체 메트릭 수집
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ykmake" # YkMake 애플리케이션 메트릭 수집
    # Docker Compose 네트워크 내 서비스 검색 사용
    # 또는 static_configs로 명시적 지정
    static_configs:
      # 'app'은 docker-compose.yml에 정의된 서비스 이름
      # 3000번 포트의 /metrics 엔드포인트
      - targets: ["app:3000"]
        labels:
          instance: ykmake-app-1 # 인스턴스 레이블 (필요시)


  # (선택 사항) Node Exporter 메트릭 수집
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
# (선택 사항) 알림 규칙 설정 (Alertmanager 필요)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093'] # Alertmanager 서비스 주소

# rule_files:
#   - 'alert.rules.yml' # 알림 규칙 파일 경로
