datasources:
  - name: Prometheus
    type: prometheus
    access: proxy # 서버(Grafana 백엔드)를 통해 접근
    url: http://prometheus:9090 # Docker Compose 서비스 이름 사용
    isDefault: true # 기본 데이터 소스로 설정
    jsonData:
      timeInterval: "15s" # 권장 스크랩 간격과 일치
    editable: false # UI에서 수정 불가
